name: Verification Tests
on:
  push:
    branches:
      - '**'
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: ./gradlew clean check
